### ISSUE TITLE
[v2017.8] test-sizes.js fails during installed-tests

### ISSUE THREAD

**Issue by smcv** [ostreedev/ostree#1014]
`test-sizes.js` seems to have regressed between 2017.7 and 2017.8:

```
Running test: libostree/test-sizes.js.test

(gjs:6459): Gjs-WARNING **: JS ERROR: Gio.IOErrorEnum: Bad file descriptor
@/usr/lib/installed-tests/libostree/test-sizes.js:47

JS_EvaluateScript() failed
FAIL: libostree/test-sizes.js.test (Child process exited with code 1)
```

That line is:

```
repo.write_directory_to_mtree(testDataDir, mtree, commitModifier, null);          
```

**Comment by smcv** [comment]
This is on an up-to-date Debian 'unstable' virtual machine, with the ostree and ostree-tests Debian packages (which I've updated to 2017.8) and no other extraneous dependencies. I'll re-test 2017.7 in the same environment to check that this is a regression in ostree and not a change in the environment.

**Comment by smcv** [comment]
> I'll re-test 2017.7 in the same environment

2017.7 (plus commits 2a082b2 and fd50c97 to make another test pass) passes all tests in an identically-constructed VM.

**Comment by cgwalters** [comment]
Yep, legit regression.  Now, the reason our CI tests didn't catch this is:

```
    gjs-based tests:                              no
```

which is actually due to the fact that the main suite uses `-fsanitize=address`, which unfortunately conflicts with introspection :disappointed:  (things blow up if one loads a shared library built with ASAN into a binary not built with it).

We could maybe define a new suite which doesn't use asan, but does run the introspection-based tests.

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1016

**Comment by smcv** [comment]
I used the one non-test commit from #1016 in Debian's ostree, which makes it pass tests on my laptop (ci.debian.net hasn't caught up with the new version yet, unfortunately). Thanks!
