### ISSUE TITLE
ostree alias: don't allow deleting ref with aliases

### ISSUE THREAD

**Issue by dustymabe** [ostreedev/ostree#1597]
`ostree-2018.3-2.fc28.x86_64`

Using aliases I can get myself in a situation where running ostree gives me an error. In this case I deleted a ref that an alias points to. I'm thinking we should require that all aliases to a ref be deleted before the ref itself can be deleted. 

```
[dustymabe@composer repo][STG]$ ostree refs
fedora/27/x86_64/updates/atomic-host
fedora/27/x86_64/atomic-host
[dustymabe@composer repo][STG]$ ostree refs --alias
fedora/27/x86_64/atomic-host -> fedora/27/x86_64/updates/atomic-host
[dustymabe@composer repo][STG]$ 
[dustymabe@composer repo][STG]$ ostree refs --delete fedora/27/x86_64/updates/atomic-host
[dustymabe@composer repo][STG]$ 
[dustymabe@composer repo][STG]$ ostree refs
error: Listing refs: openat(fedora/27/x86_64/atomic-host): No such file or directory
```

**Comment by ashcrow** [comment]
Follow up on this ... did any work start or is this still a brand new item?

**Comment by jlebon** [comment]
It's still a brand new item.

**Comment by sinnykumari** [comment]
To fix this issue, when someone tries to run `ostree refs delete REF` and REF has some aliases then instead of deleting REF we will display a message saying that "REF has some aliases, please first delete all aliases referred by REF".

Does it make sense to also have a `--force` option which will allow user to delete REF along with all corresponding aliases? In this case user is aware of that REF having aliases and would like to delete both REF and corresponding aliases in a single run `ostree refs --force --delete REF`

**Comment by dustymabe** [comment]
> Does it make sense to also have a --force option

seems reasonable. I'll defer to colin/jonathan though

**Comment by sinnykumari** [comment]
@cgwalters @jlebon Thoughts?

**Comment by cgwalters** [comment]
We could also convert aliases to non-aliases when their target is deleted.

I don't have a strong opinion on this; defaulting to making it an error seems fine, we can always add `--force` later.

**Comment by sinnykumari** [comment]
Thanks @cgwalters for the input. To me defaulting to error message sounds a better option, will work on implementing same.
