### ISSUE TITLE
Rework ostree_repo_get_min_free_space_bytes ()

### ISSUE THREAD

**Issue by uajain** [ostreedev/ostree#1720]
In https://github.com/ostreedev/ostree/pull/1715 I added an API to query the `min-free-space-*` config option in a format(`bytes`) which could be useful to application like gnome-software via flatpak wrapper around it. The specific use case for Endless is to place a heuristic around (free-space vs. required space for app-install/update) which can determine(with some probability) if the operation will be successful or not, given the disk-space situation. It also took min-free-space-* into account hence, the genesis for this API.

The min-free-space-* config option is actually parsed into a usable form(`bytes`) during the `prepare_transaction()`. Therefore, while writing this API, I made sure the API is usable only if there is an ongoing transaction so that the value of the option remains consistent and doesn't return inconsistent values outside transaction (which can happen if the config's value is changed in the configuration).

It seems that I have made a mistake that this API can only be read during transaction. The heuristics we place in gnome-software wants to read the `min-free-space-*` option even before the transaction is started by flatpak. Currently it's hard-coded but the eventual goal was to use this API.

Other workarounds suggested is to start and abort a transaction to get the value out with the existing API. 

Please consider this issue as a release blocker. We need collective thinking and how this can rework-ed.

**Comment by dbnicholson** [comment]
Why does the transaction come until play at all? Why not just parse the options once when the repo is opened like 90% of the other repo options? Or just split out the passing to a helper that gets called by the API and when beginning a transaction. Or just call the API when beginning a transaction. As far as I know there's nothing transaction specific about looking at the filesystem stats and the repo options.

**Comment by ramcq** [comment]
Our motivation for adding this was pre-determining whether an operation in GNOME Software will succeed or fail, before we start taking repo locks or doing any disk IO etc. I think opening a transaction ends up writing to disk?

The combination of the volume disk IO/fsyncs around an ostree operation, the fact that the flatpak user -> system pull uses 2x disk space during that operation, and that we're enabling auto updates by defaults, is pretty bad: we're seeing machines which low on disk space getting into loops where they try to auto update, killing interactivity / usability of the machine, fail, then come back and do it again a few hours later. So, your disk is left close to (because Flatpak saves the user repo in /var/tmp), your computer runs really slow, and spits errors randomly about failing updates / low disk. It's pretty cool.

So we're adding some heuristics into GNOME Software to preclude starting an auto-update if we don't have 2x installed size + min-free-space available (and different numbers like download size for installs etc). We wanted to get that magic number as cheaply as possible in order to cut the load to ~0 of the auto-update heuristic.

**Comment by dbnicholson** [comment]
> The value in bytes will change as the free space on the disk changes. And we only compute the free space when starting a transaction.

Sure, making the check at the beginning of the transaction is very useful and should stay. However, I don't see any reason why the calculation has to happen inside a transaction. It's just `statvfs()` and some math, right? As an API, it seems unnecessarily restrictive to require a transaction to get the results of the calculation.

**Comment by dbnicholson** [comment]
Or, to ask another way, what does a transaction provide to make the calculation valid?

**Comment by uajain** [comment]
@dbnicholson Made a quick PR, if you want to take a look. I think you are right.

**Comment by pwithnall** [comment]
The reason the implementation we ended up with did the calculations when starting a transaction was partially to avoid any possibility of having to return a `GError` on the `get_min_free_space_bytes()` getter. It would be perfectly possible to add another version of it, or change it, to expose a `GError**` and do the `statvfs()` and free space calculation again when called, as well as when starting a transaction.

**Comment by uajain** [comment]
[PR merged](https://github.com/ostreedev/ostree/pull/1722)
Closing.
