### ISSUE TITLE
/sysroot private mount and /home -> /sysroot/home

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#2086]
Related: https://github.com/ostreedev/ostree/issues/2085

Reported on IRC, today gnome-continuous uses `/home` :arrow_right: `/sysroot/home` but this conflicts with https://github.com/ostreedev/ostree/pull/1438 if the user creates mounts in their home directory.

I think basically everyone should use `/var/home`, but probably ostree should either disable the private mount for `/sysroot` if we detect these symlinks.

**Comment by valentindavid** [comment]
I have noticed that if I remove totally `/home` :arrow_right: `var/home`, then Flatpak applications with `--filesystem=host` do not have access to home directory, unless they also have `--filesystem=home`. 

So it seems that home should be defined within `/var/home` in `/etc/passwd`, but the symlink should still exist for flatpak application to work correctly. (I still have to test that).

**Comment by jlebon** [comment]
> So it seems that home should be defined within `/var/home` in `/etc/passwd`

Yes, note rpm-ostree for example does this: https://github.com/coreos/rpm-ostree/pull/1726.

**Comment by valentindavid** [comment]
I can confirm that for Flatpak applications like org.flatpak.Builder need to have both the `/home` :arrow_right: `var/home` AND the home directory defined in `/etc/passwd` should be using `/var/home`. I have just tested it.

It is very peculiar that removing the symlink breaks flatpak.

**Comment by dbnicholson** [comment]
We hit a very related issue in Endless OS recently that's caused by `/sysroot`'s private mount propagation. We have a test mode that mounts an overlay on /sysroot (and other disk backed mounts) so that you can make broad changes to the
system and have them discarded when the system is shut down. If a process is started with a separate mount namespace before test mode is invoked, then that process will not inherit the /sysroot overlay. This was causing new user home directories to persist in /sysroot/home since accountsservice started using systemd sandboxing features a couple years ago, but it just hit Endless OS early this year and apparently no one has run the test mode since.

As it turns out, I think private `/sysroot` is solving the problem the wrong way. That was added to prevent submounts in `/var` from propagating back to `/sysroot/deploy/.../var`. That's very useful, but private mount propagation is a very large hammer for it since it stops all mount propagation. Instead, I think it's better if `/sysroot` is the default shared and `/var` is made a slave so that it receives mount events from `/sysroot` but not vice versa. Then you retain the behavior that `/var` submounts don't propagate back to `/sysroot`, but submounts of `/sysroot` propagate in the completely normal way. This is how systemd and toolbox setup mount namespaces.
