### ISSUE TITLE
Enable sysroot.readonly at initrd time

### ISSUE THREAD

**Issue by jlebon** [ostreedev/ostree#2115]
Follow-up from https://github.com/ostreedev/ostree/pull/2113. Instead of enforcing it at `ostree-remount` time, which runs in the real root, we should try to have it already be read-only from the start.

**Comment by lucab** [comment]
This is still affecting users due to several possible races, so it would be good to push it a bit forward.
I saw @cgwalters attempted moving it to initrd at https://github.com/ostreedev/ostree/pull/2187, but I do wonder whether that one as well may prone to races with the rest of initrd services.

I started considering placing this into a systemd-generator instead, and put together a quick bash generator to explore that path. It's up at https://github.com/coreos/fedora-coreos-config/pull/1257 and passes FCOS CI.

These are my findings so far:
 * `/run/ostree-sysroot-ro.stamp` is used both as a stamp file and as a boolean flag for RO/RW. This breaks upon re-execution, because we unlink in the first run and then check its presence in the second run. We should probably not use it as a stamp file, or have a persistent signaling file somewhere else (maybe we do already and I'm just not aware of it).
 * `ostree-remount` handles both `/sysroot` and `/var` remounts. The former can be safely done early on, in initrd or in a generator. The latter unfortunately has to be handled in a different way (later or with more complex logic) because there may be a `var.mount` unit in the real rootfs.
 * The logic handling `/var` is inherently subject to races, because the bind-mount operation cannot do the RO/RW switch at the same time. There is thus a window where the `/var` mount exists but may still need to be remounted.
 * I don't see a good way to avoid `/var` races with arbitrary services, only through systemd dependencies. I think a generator is the way to minimize the chances of races, as there aren't many things running at that point. Unfortunately that does require some logic to detect more complex cases (custom `var.mount`, live systems, etc.), which may be a bit fragile at least initially.

**Comment by cgwalters** [comment]
> I saw @cgwalters attempted moving it to initrd at #2187, but I do wonder whether that one as well may prone to races with the rest of initrd services.

I think the initramfs is a much more constrained environment *and* the entire goal of the initramfs is to prepare `/` with various hook points for that.  So we *should* be able to do this in the initramfs.

Another argument for doing so is it's similar to what we do for the CoreOS live environment today: https://github.com/coreos/fedora-coreos-config/blob/08954efa915abd3e52240935d7e27235388f5533/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-live/live-generator#L173 

> I started considering placing this into a systemd-generator instead

But, yes this is a strictly more powerful way of doing things in the real root.  We actually already have a generator to do exactly this type of stuff https://github.com/ostreedev/ostree/blob/main/src/switchroot/ostree-system-generator.c

So that generator could be enhanced to control the timing of `ostree-remount.service` too.

But it's not clear to me that this really helps versus moving it to the initramfs.

**Comment by jlebon** [comment]
> This is still affecting users due to several possible races, so it would be good to push it a bit forward. I saw @cgwalters attempted moving it to initrd at #2187, but I do wonder whether that one as well may prone to races with the rest of initrd services.

Can you expand on this? If we set up `/var` from `ostree-prepare-root.service` as part of setting up the sysroot itself, there shouldn't be any race possible, no?

Conceptually, I think this would be equivalent to upstreaming [`ignition-ostree-mount-var.service`](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-mount-var.service) and [`.sh`](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-mount-var.sh) (but making it part of `ostree-prepare-root.service` instead) and just leaking the `/var` bind-mount into switchroot. I guess the simplest way to deal with a potential other `var.mount` is to just let it overmount the OSTree bind-mount, like we currently do [in the initrd](https://github.com/coreos/fedora-coreos-config/blob/08954efa915abd3e52240935d7e27235388f5533/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-mount-var.service#L18-L19). Though it does make the mount hierarchy uglier.

**Comment by jlebon** [comment]
Instead of leaking `/sysroot/var`, would it work to have `ostree-prepare-root` make `/ostree/deploy/fedora-coreos/var` a bind-mount onto itself that's rw? So then the default `var.mount` bind-mount should (I *think*) still retain the rw property since it's from a bind-mount and not directly the ro rootfs.
