### ISSUE TITLE
v2020.4 triggers assertion failure when upgrading with deployments with device trees

### ISSUE THREAD

**Issue by akiernan** [ostreedev/ostree#2154]
New in v2020.4 compared to v2020.3:

```
root@gvt-441:~# ostree admin deploy 331814d256100fe9dd08b1c75f59b2cb3880877713d9a78af5a81b1a1c1acdaf
[   69.732284] EXT4-fs (mmcblk0p2): re-mounted. Opts:
[   69.737492] ext4 filesystem being remounted at /sysroot supports timestamps until 2038 (0x7fffffff)
Copying /etc changes: 2 modified, 3 removed, 10 added
[   88.382227] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   88.390336] ext4 filesystem being remounted at /boot supports timestamps until 2038 (0x7fffffff)
**
OSTree:ERROR:../git/src/libostree/ostree-sysroot-deploy.c:1775:install_deployment_kernel: assertion failed (kernel_layout->bootcsum == bootcsum): ("4f3375c34a0e378b04bdfc77d82d75d6f726c4cf065e048f22e9ba7df0617163" == "f71de0cbc10f1dd60423c02c280317742d329a2fc0eba5eeab2282291bde1935")
Bail out! OSTree:ERROR:../git/src/libostree/ostree-sysroot-deploy.c:1775:install_deployment_kernel: assertion failed (kernel_layout->bootcsum == bootcsum): ("4f3375c34a0e378b04bdfc77d82d75d6f726c4cf065e048f22e9ba7df0617163" == "f71de0cbc10f1dd60423c02c280317742d329a2fc0eba5eeab2282291bde1935")
```

Can't immediately see a commit which is causing this, so starting to bisect it.

**Comment by cgwalters** [comment]
Hmm possibly https://github.com/ostreedev/ostree/pull/2001 ?

**Comment by akiernan** [comment]
> Hmm possibly #2001 ?

That was my first thought, but I definitely tested that one at the time (though I probably just brought that commit in rather than the whole tree).

**Comment by akiernan** [comment]
> > Hmm possibly #2001 ?
> 
> That was my first thought, but I definitely tested that one at the time (though I probably just brought that commit in rather than the whole tree).

Clearly my testing was rubbish, because that's the commit that breaks it.

**Comment by jlebon** [comment]
To clarify, this only fails when you're using device trees, right? Or are you seeing failures even when deploying an OSTree without? That would be much worse.

**Comment by akiernan** [comment]
I suspect it's the deploy without device tree case that's broken, I need to dig a bit more. Whilst I have a device tree, it's embedded in the kernel image as part of a FIT image; I suspect when I tested, I only tested with a dtb directory/separate device tree file - neither of which I have for the FIT case.

**Comment by cgwalters** [comment]
One potential problem I see: ostree < 2020.4 and ostree ≥ 2020.4 are going to calculate the boot checksum differently.  I think then we could have a problem when upgrading across them.

**Comment by agners** [comment]
Sorry about the breakage.

I remember having seen such missmatch messages also due to ordering when deploying multiple device trees in a single directory (since the fs does not guarantee any ordering). I then added sorting and did not see any such problems anymore: https://github.com/ostreedev/ostree/pull/2001/files#diff-f0c889fb056dc4a713f8a87702fdd27eR258

But I guess this is a different case.

So is OSTree "validating" the checksum of old boot deployments? Wouldn't it just create a new boot deployment if the checksum does not match?

**Comment by akiernan** [comment]
> One potential problem I see: ostree < 2020.4 and ostree ≥ 2020.4 are going to calculate the boot checksum differently. I think then we could have a problem when upgrading across them.

I think that's what I'm seeing, it also explains why all my attempts at reproducing the problem with a test case failed.

I've built from scratch a box starting with ostree 2020.4 and can quite happily upgrade across deployments within that version. If I build an image with 2020.3, whilst I can switch to that, I can't then switch back - which basically mimics the failure here, but starting for 2020.3.

**Comment by cgwalters** [comment]
We need to decide whether to:

- Assume most people aren't depending on 2020.4 yet and revert the change, release 2020.5, then revisit
- Make it a build time option
- Block on fixing this (needs some thought)

**Comment by jlebon** [comment]
Hmm, I think we can just always take the freshly calculated bootcsum as the source of truth of how to refresh the layout of files in `/boot`? IOW, we'd drop the assertion that's triggering and disregard the bootcsum associated with the deployment object (since it might've been calculated using an older algorithm).

**Comment by cgwalters** [comment]
The deployment → bootcsum link is used for garbage collection of the bootloader data.  The ramifications of having different versions of ostree disagree on that is hurting my head a bit - if we remove the assertion, then upgrading old → new, the new version would think its bootloader data should be pruned...we could instead change things so that we instead add *both* checksums into our referenced set.

So maybe the safest fix here is "calculate the boot checksum both the old and new way, and accept either"?

**Comment by akiernan** [comment]
> So maybe the safest fix here is "calculate the boot checksum both the old and new way, and accept either"?

I think that fixes stuff if your direction of "upgrade" is only towards newer versions, but if I say have an image which is based on 2020.4 and then "upgrade" to something which uses 2020.3, then I'll be stuck unable to move from that version... I can think of examples in our estate where that could happen (although not something we usually do, but say we decide to rollback  a release once we're in early deployment).

The other example I think it would break completely for us is across our test estate where we reuse devices running against several release branches as they pop out of CI.

I'm wondering if an additional flag in the config could indicate which checksum is in use? So you can opt in to the new behaviour, but don't get it by default?

**Comment by agners** [comment]
Why is the checksum even different? I don't think that was the intention here for all but the new use case. So unless there is a `dtb/` directory in the kernel modules directory, the checksum really should be the same.

Of course if there was already a `dtb/` in the OSTree, then the checksum will change. But we must have have the same problem in the past adding other boot artefacts, such as the initial device tree support in https://github.com/ostreedev/ostree/pull/1411.

**Comment by akiernan** [comment]
> Why is the checksum even different? I don't think that was the intention here for all but the new use case. So unless there is a `dtb/` directory in the kernel modules directory, the checksum really should be the same.

You're spot on - that's why I'm seeing this. I have a `dtb` directory which, whilst unused, is present. If I remove that from my image generated with 2020.4 then I can happily upgrade/downgrade 2020.3 <=> 2020.4.

So I think with that change in the image I construct from, then I no longer have an issue, though I'm just trying to work out if that directory existing within an older image is going to cause me (or others) flag day type problems.

**Comment by akiernan** [comment]
> I have a dtb directory which, whilst unused, is present.

Just to clarify, an empty `dtb` directory doesn't trigger the issue, you need files in there to trigger it.

**Comment by agners** [comment]
> Just to clarify, an empty dtb directory doesn't trigger the issue, you need files in there to trigger it.

I was wondering if `.` and `..` might end up in the checksum. But ok it seems not then. Thanks for the investigation and update!

**Comment by cgwalters** [comment]
> So I think with that change in the image I construct from, then I no longer have an issue, though I'm just trying to work out if that directory existing within an older image is going to cause me (or others) flag day type problems.

I think it will, unless we change ostree to compute and accept both checksums, it is indeed a "flag day" for OS creators like you who have a `dtb/`.  I have no idea how common that is though - am I correct in that the directory existed before, but was being ignored?

That said,for FCOS we use https://github.com/coreos/zincati/ which gives clients an "upgrade graph" - and one could use that type of approach to fix this as follows:

- v0: Update that uses ostree < 2020.4 and removes the `dtb/`
- v1: Update with ostree 2020.4, and still no `dtb/`
- v2: Update that adds `dtb/`

 Change the upgrade graph to force clients to upgrade from 1 → 2 → 3 or so.

(One can also implement a Zincati-like model without any client side agent by using ostree branches to model epochs, and have a small bit of code that `ostree admin switch` across them)

**Comment by jlebon** [comment]
> I have a dtb directory which, whilst unused, is present. If I remove that from my image generated with 2020.4 then I can happily upgrade/downgrade 2020.3 <=> 2020.4.

Cool, that's good news. I retitled the issue so it's clear this is limited to clients which use device trees.

> The deployment → bootcsum link is used for garbage collection of the bootloader data. The ramifications of having different versions of ostree disagree on that is hurting my head a bit - if we remove the assertion, then upgrading old → new, the new version would think its bootloader data should be pruned (that's why the assertion exists)...

Ahh OK. My understanding was that we recompute from scratch each time the files that need to be added to `/boot` on every finalization. So IOW, it'd be fine if the previous deployment's bootcsum dir would get blown away since we'd also be creating the new bootcsum dir paired with the right BLS entries for it.

**Comment by akiernan** [comment]
> > So I think with that change in the image I construct from, then I no longer have an issue, though I'm just trying to work out if that directory existing within an older image is going to cause me (or others) flag day type problems.
> 
> I think it will, unless we change ostree to compute and accept both checksums, it is indeed a "flag day" for OS creators like you who have a `dtb/`. I have no idea how common that is though - am I correct in that the directory existed before, but was being ignored?
> 

Yes, that's correct - it was present, but ignored.

**Comment by travier** [comment]
It looks like this is also impacting Fedora IoT, here installed on a Nanopi Neo 2:
```
Sep 07 15:55:35 localhost.localdomain ostree[6634]: Copying /etc changes: 6 modified, 7 removed, 30 added
Sep 07 15:55:35 localhost.localdomain ostree[6634]: Copying /etc changes: 6 modified, 7 removed, 30 added
Sep 07 15:55:42 localhost.localdomain ostree[6634]: **
Sep 07 15:55:42 localhost.localdomain ostree[6634]: OSTree:ERROR:src/libostree/ostree-sysroot-deploy.c:1775:install_deployment_kernel: assertion failed (kernel_layout->bootcsum == bootcsum): ("5dc0ba247597d5e88bca607be1aee8e88aafc0c6e80990d1025f0d2a18c8dc58" == "819033c3c33813ae3447500b0eb78073a68caf4f924431efd5a4b63d6bc23117")
Sep 07 15:55:42 localhost.localdomain ostree[6634]: Bail out! OSTree:ERROR:src/libostree/ostree-sysroot-deploy.c:1775:install_deployment_kernel: assertion failed (kernel_layout->bootcsum == bootcsum): ("5dc0ba247597d5e88bca607be1aee8e88aafc0c6e80990d1025f0d2a18c8dc58" == "819033c3c33813ae3447500b0eb78073a68caf4f924431efd5a4b63d6bc23117")
```

Due to this I can not overlay any package.

**Comment by agners** [comment]
It probably affects pretty much every Fedora IoT board which does make use of dtb directory. Using that folder was a rather conscious design decision back then, since I wanted to use a directory which is used by upstream distributions already:
https://github.com/ostreedev/ostree/issues/1900#issuecomment-581542179

In hindsight, this was a bad idea... I wasn't aware of the problematic that when we change the files which make up the boot hash, we actually break existing installations.

This must have been an issue already in the past, e.g. when `devicetree` support got added in https://github.com/ostreedev/ostree/commit/720e2ec9bc401ec82deb64d5f493d5a2a41dd87d. However, I guess since just a bare `devicetree` file wasn't really common back then, it has not been noticed.

**Comment by cgwalters** [comment]
I think we need to change ostree to calculate the checksum with and without DT and honor either.

**Comment by jlebon** [comment]
FYI, we're working on reverting this in Fedora: https://src.fedoraproject.org/rpms/ostree/pull-request/18.

> I think we need to change ostree to calculate the checksum with and without DT and honor either.

How about a slight tweak on this: check whether the bootcsum dir has a `dtb/` in it. If it does, then it must've been created by new OSTree, so to match it we include it in our checksumming. If it doesn't, then it must be from the old OSTree, so we don't include it in our checksumming. This avoids us having to checksum two different ways in one pass and just compare the deployment bootcsum against a single checksum.

@agners Would you be interested in implementing and testing the workaround suggested here?

**Comment by cgwalters** [comment]
I'll take this.

**Comment by cgwalters** [comment]
One ugly thing here is we're still carrying the code for `/usr/lib/ostree-boot/{vmlinuz,initramfs.img}-$checksum` where that checksum was computed *server* side, which means that a total of 3 potentially distinct versions of ostree can be in play:

- the version used at build time
- the booted version
- the upgrade target commit

However...today rpm-ostree defaults to injecting into "both" (and FCOS overrides to use solely `modules`) and we prefer the former...so I'm just going to ignore the case for people not using `/usr/lib/modules` right now.

**Comment by cgwalters** [comment]
> How about a slight tweak on this: check whether the bootcsum dir has a dtb/ in it.

What do you mean by "the bootcsum dir"?  The one we're *currently* running?  I think that would work in the common case of upgrading from "no dtb" to "dtb" cases, but doesn't solve the other problems that can arise when mixing versions of ostree on a system.  A simple variant is the "installer" case like anaconda.

In a multi-boot scenario for example if you booted into an old ostree it could...well, actually I guess right now we just "trust" the bootcsum and don't try to validate it, so you wouldn't end up getting bootdirs pruned incorrectly.

Blah, ultimately I think we probably need to stop using checksums here - all we need is a way for a deployment to hold a reference on a bootloader directory or so?  Hmm.

**Comment by cgwalters** [comment]
I first wanted to get an easy reproducer for this, that's in https://github.com/ostreedev/ostree/pull/2202

**Comment by jlebon** [comment]
Was thinking some more about this. All we care about is that the `OstreeDeployment` objects have a bootcsum which matches what's in `/boot` so that sysroot cleanup doesn't blow it away.

Since we don't actually wipe the old bootcsums until an explicit sysroot cleanup, if we're interrupted while e.g. iterating over the new deployments, it doesn't matter since the old bootconfigs still hold a "ref" on the old bootcsums (a cleanup at that time would wipe the new bootcsums, not the old ones).

IOW, the way I think of this: it doesn't matter if bootcsums for the same deployment isn't the same across OSTree versions. The bootconfigs hold the source of truth for binding deployments to bootcsums, and that gets updated atomically during the `/boot/loader` symlink rename.

So this means we can completely ignore the deployment's bootcsum (i.e. drop the assertion we're tripping) in `install_deployment_kernel`.

Once we do the symlink swap, the sysroot reload we do will update the in-memory OstreeDeployment objects with the correct `bootcsums`.

**Comment by cgwalters** [comment]
Updated https://github.com/ostreedev/ostree/pull/2202
