### ISSUE TITLE
Seeking help to port Feroda-IoT

### ISSUE THREAD

**Issue by Darsh-Dev** [ostreedev/ostree#2264]
Hi,

We are working on a project in which we need to port Fedora-IoT rootfs on iMx8 (NXP) board. Below is the approach we have taken and queries we have.

We have taken the Linux kernel from NXP version - Kernel 5.4.47-2.2.0+g88d90ad100ab on an aarch64 and u-boot from also NXP.

We have extracted the rootFS from the binary on the below link.

https://getfedora.org/en/iot/download/

SD card structure we have made for the imx8 board - Fedora-IoT rootfs:

u-boot will be copied on SD card using dd command

boot partition - dtb and kernel images

root partition - Fedora IoT rootfs

After successful boot up of the board we got below logs:

Fedora 33.20201215.0 (IoT Edition) Kernel 5.4.47-2.2.0+g88d90ad100ab on an aarch64 (ttymxc0)

Browse to https://provision.fedoraproject.org to claim this device (device ID not yet known) and configure SSH keys deployed

localhost login: root

Password:

Below command is not working for us and it halts all the installation process, which stops other main activities.

[root@localhost ~]# rpm-ostree status

error: loading sysroot: Unexpected state: /run/ostree-booted found and in / sysroot, but bootloader entry not found

Could you please help us over here?

Regards,

**Comment by lucab** [comment]
Thanks for the report, but this doesn't look like a bug in ostree. Your output shows rpm-ostree not finding the expected bootloader entries, which could be due to the way you installed the image. Feel free to reach out to the Fedora IoT folks at https://discussion.fedoraproject.org/c/server/iot/7 for further help about bootloader configuration.
