### ISSUE TITLE
Is it possible to find the "creator"/"owner" of a deployed file?

### ISSUE THREAD

**Issue by Mershl** [ostreedev/ostree#2433]
Background:
On one of my systems I have a `/usr/etc/authselect/user-nsswitch.conf.bak` file which I can't make sense of. Is there a tool or log available that could help me pinpoint the creator/owner/source of it?

**Comment by dbnicholson** [comment]
It's entirely dependent how you construct the commit. Ostree just puts in the files you tell it to. If you're doing a layered commit like with `rpm-ostree` you could look at each of the layers to see when it shows up. More likely you'll just need to instrument your own build process.

I'm going to close this since I don't think there's anything ostree itself can do to help.
