### ISSUE TITLE
test-cli-extensions.sh fails with symlinked env

### ISSUE THREAD

**Issue by jtojnar** [ostreedev/ostree#2553]
On systems where `coreutils` are built with `--enable-single-binary=symlinks` like Nix,  `/usr/bin/env` is symlinked to `/usr/bin/coreutils` and uses `argv[0]` to determine which program to run. Since the `test-cli-extensions.sh` [creates a new symlink](https://github.com/ostreedev/ostree/blob/00e39ebedc28e2f4d3b86ab5993ca67d9f1ed217/tests/test-cli-extensions.sh#L18) named `ostree-env`, running it will fail:

```
ostree-env: unknown program ‘ostree-env’
Try 'ostree-env --help' for more information.
```

**Comment by lucab** [comment]
Thanks for the report. I introduced this test regression because I didn't know `env` was also relying on `argv[0]` dispatching on Nix.
I currently don't have better suggestions for an alternative to this. But I think it may be enough to run this test where `env` is a regular executable (like on our CI) and plainly skip on those environments where it is detected as a symlink.

**Comment by jtojnar** [comment]
One alternative might be something like:

```
echo '#!/bin/sh' >> ./localbin/ostree-env
echo 'env "$@"' >> ./localbin/ostree-env
chmod +x ./localbin/ostree-env
```

We can skip the test as well – though we would need to also add an ignore option to `gnome-desktop-testing-runner`, if we do not want to patch the test out.

**Comment by lucab** [comment]
@jtojnar if that works for Nix, it should be fine for the CI here too. Could you maybe try a patch like that locally and then push it to a PR if it works?

**Comment by jtojnar** [comment]
Opened a PR with the fix: https://github.com/ostreedev/ostree/pull/2573
