### ISSUE TITLE
2022.3 stopped working with flatpak-builder

### ISSUE THREAD

**Issue by tim77** [ostreedev/ostree#2604]
`2022.3` stopped working with `flatpak-builder`. Got this error when trying to build:

```
fuse: unknown option(s): `-o splice_write,splice_move'
```
OS: Fedora 36. Update currently in [Bodhi](https://bodhi.fedoraproject.org/updates/FEDORA-2022-893b870b9b#comment-2523203) and Testing repos.

**Comment by cgwalters** [comment]
Likely fallout from https://github.com/ostreedev/ostree/pull/2376 and https://src.fedoraproject.org/rpms/ostree/c/039a8271a736618e04313621ee2435e5758a4ded?branch=rawhide

I think because I used merge that latter change got backported to 36.

That links to https://src.fedoraproject.org/rpms/flatpak-builder/c/44e61ac73aaab42d
which I think we need for f36 too.

**Comment by cgwalters** [comment]
https://src.fedoraproject.org/rpms/flatpak-builder/pull-request/2

**Comment by cgwalters** [comment]
Closing because no action is required from ostree side here.

(I actually want to officially deprecate rofiles-fuse and move it to a separate repo)

**Comment by tim77** [comment]
@cgwalters thanks. Can i help with testing or something? Probably i should try https://src.fedoraproject.org/rpms/flatpak-builder/pull-request/2. As soon as i can.
