### ISSUE TITLE
ima: Support signing metadata objects and checkout fs tree validation

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#2609]
Today [ostree's IMA signatures](https://ostreedev.github.io/ostree/ima/) supports signing regular file objects.  However, there are holes in this model; classically, IMA alone won't detect e.g. swapping two signed binaries, or replacing one signed binary with an older, insecure version etc.

However, we can implement a model where we do a "structural fsck" from the initramfs.  Assuming that the initramfs is signed and verified (e.g. as part of a Secure Boot flow), then we would (from inside the initramfs):

- Load the target commit object
- Perform signapi (GPG/builtin ed25519) + content checksum verification of the target commit object *or* use IMA/fsverity for the commit object directly (it makes total sense to reuse IMA as another commit signature mechanism)
- Perform "structural verification"; walk over the target physical rootfs and verify *directories* and *symlinks* but not regular file contents

Thinking of directories and symlinks as metadata and regular files as data - we're verifying all metadata up front, and then relying on the dynamic IMA (and future fsverity) signature for all the (much larger) regular files. 

This was motivated by this sub-thread https://twitter.com/cgwalters/status/1520465975719645184 and this blog https://0pointer.net/blog/fitting-everything-together.html

Vs dm-verity in particular, I think what we're trading off here is really an echo of the larger picture of ostree-style updates (file based) versus block device updates.  File updates are much, much more flexible and we can do things like deduplicate shared space trivially.  There's not a "hard cap" on disk size beyond which the OS cannot grow, and similarly there's not "unused dead space".

Now that blog says:

>  I think validation is still at too high a level, since Linux file system developers made very clear their implementations are not robust to rogue images.

But yes, see e.g.: https://lwn.net/Articles/755593/

OTOH, as long as the machine has *any* persistent Linux filesystems it mounts and reads from the kernel, they could also be exploitable in a similar fashion.  For "offline" AKA "evil maid" attacks, this is hopefully somewhat mitigated by dm-crypt; I suspect it'd be hard to corrupt the rootfs offline in such a way that it would be corrupted exploitably, but I am not aware of much research on this.

**Comment by alexlarsson** [comment]
@cgwalters So, should we move this to ostreedev/ ?

**Comment by alexlarsson** [comment]
So. I've got code to compute fs-verity hashes for a file, so I can easily compute alternative digest for file objects which are based on fileheader + fs-verity-hash. However, I've been looking for a good way to inject these into the the metadata that is cheaply verifiable from the commit, which consists of the commit, dirmeta and dirtree objects. "Unfortunately", ostree is very strict about these, including things like enforcing normalized gvariants, so I was unable to find a good spot to inject these. The only two realistic places we can extend things are the commit object metadata and the directory entry xattr. 

The first place I looked at was the directory entry attr. This is not ideal, as now the directory metadata depends on the contents, which is going to change as the files change. It also is practically quite nasty to implement given how commit works in terms of mutable trees. The directory metadata is serialized very early in the commit operation, before building the final directory structure. There are also issues with how this will work with checkouts of the commit. For a directory with 1000 files, the digest list will be 32k, and I'm not sure any filesystems can actually store xattrs of that size.

So, the next location is to put something in the commit metadata. This is rather expensive, as it would need to be a full mapping of file digest to fs-verity digest. I have an example, quite small (700M) cs9-based commit I'm testing things with. It has 16k files in it, so would need at least 1MB for a digest mapping table. This isn't really something we realistically can handle.

I've also thought about adding some generated dotfile in the actual commit with the mappings, but that has similar issues to the xattrs.

 Basically, I'm having a hard time actually adding something to the commit metadata at all.

Then it struck me. We don't actually have to store anything in the commit. All the extra information we want to add to the commit is computable on the client from the information we have in the commit. So, we would define a virtual mapping from the set of files in the commit to the fs-verity manifests. The exact format isn't important as long as it is 100% reproducible. We generate such a mapping on the server just so that we can fs-verity hash it and store that hash in the commit. The client can then reconstruct this mapping locally, seal it with fs-verity, and the kernel filesystem can safely trust the mapping as long as it is fs-verity hashed and matches the hash stored in the commit.

Does that make sense?

**Comment by cgwalters** [comment]
> To start with I wrote a userspace version of the fs-verity merkletree digest. Got that working now.

Isn't that https://git.kernel.org/pub/scm/linux/kernel/git/ebiggers/fsverity-utils.git/tree/include/libfsverity.h#n184 ?

**Comment by alexlarsson** [comment]
> > To start with I wrote a userspace version of the fs-verity merkletree digest. Got that working now.
> 
> Isn't that https://git.kernel.org/pub/scm/linux/kernel/git/ebiggers/fsverity-utils.git/tree/include/libfsverity.h#n184 ?

I was not aware of that, but having a more generic (GInputStream) implementation will make it easier to integrate with ostree (for example, handling archive mode repos with compressed files, etc), and its not really complex: https://gist.github.com/alexlarsson/765c7f2344c03d80514f0c20ee08560d

**Comment by cgwalters** [comment]
> @cgwalters So, should we move this to ostreedev/ ?

Yep fine by me!  Though I do still feel ultimately this shouldn't be completely tied to ostree, we really want something like "veritytreefs" or so right?  At least with support for mtimes...and in the general case perhaps everything OCI supports, such as sockets.  But definitely good to have it in the ostreedev GH organization; should help with reviews, visibility, permissions etc.

I think all you need to do is [this flow](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account).

**Comment by cgwalters** [comment]
> The client can then reconstruct this mapping locally, seal it with fs-verity, and the kernel filesystem can safely trust the mapping as long as it is fs-verity hashed and matches the hash stored in the commit.

Yeah, I think that makes sense.  It's basically the same as how the fsverity approach works for the *content* of files right?  The tree is reconstructed on the client, the approach relies on the server and client computing the same thing.

**Comment by alexlarsson** [comment]
Moved to https://github.com/ostreedev/ostreefs

**Comment by alexlarsson** [comment]
> > @cgwalters So, should we move this to ostreedev/ ?
> 
> Yep fine by me! Though I do still feel ultimately this shouldn't be completely tied to ostree, we really want something like "veritytreefs" or so right? At least with support for mtimes...and in the general case perhaps everything OCI supports, such as sockets. 

Yeah, I guess the question is if we want to do this by extending the ostree to optionally include this (via xattrs I guess), or if we would want to completely change things in a way that is incompatible with the current ostree format. For example, such a changed format could natively use the fs-verity hash for file contents, rather than plain sha256. 

However, this would be a very large change that would invalidate large parts of the ecosystem around ostree. I think extending the ostree format for this would make more sense. The extensions needed are not that large, and then you can use the existing software and infrastructure around ostree.

**Comment by alexlarsson** [comment]
What about this approach:

Instead of checking out a commit when we deploy it, we generate a composefs metadata file for the commit, using the ostree repo for file content (but not for directory and file metadata). This is done in a reproducible fashion, and includes the fs-verity checksums for the file contents. Then this file is mounted, instead of the checkout.

Additionally, during commit, ostree computes the same composefs metadata file and adds its digest to the commit. We can then verify that the computed composefs file matches what is in the commit.

**Comment by alexlarsson** [comment]
For people who want to follow this, i've done a lot of work for this in composefs: https://github.com/giuseppe/composefs
