### ISSUE TITLE
dracut module should be opt-in

### ISSUE THREAD

**Issue by tinywrkb** [ostreedev/ostree#2723]
Installing the ostree dracut module into `/etc/dracut.conf.d` injects it by default into the initramfs, and forces it on users who most likely don't care about ostree operating system distribution, deployment and admin capabilities.  
IMO this is wrong, and the module should be installed instead into `/usr/lib/dracut/modules.d`.

**Comment by dbnicholson** [comment]
The module is installed in `/usr/lib/dracut/modules.d`. But the configuration is put in `/etc/dracut.conf.d` by default. I just found out there's a separate `--with-dracut=yesbutnoconf` option that I'd never seen before. So, you can do that right now. However, I think the way that most distros handle this is to split the dracut (and other boot related parts) into a separate package. The idea is that if you install the ostree boot parts, you actually really want the dracut module to be enabled since it's required.

If you want to send a patch that more clearly documents that `yesbutnoconf` value or add a separate `--with-dracut-conf` option, I think it would be accepted.

**Comment by dbnicholson** [comment]
On the other hand, if you're not using the boot parts, then why enable the dracut module at all? The entire reason it exists is to help you boot into an ostree managed system.

**Comment by cgwalters** [comment]
The `--with-dracut=yesbutnoconf` is the intended fix for this.
