### ISSUE TITLE
I can't build this on wsl (ubuntu)

### ISSUE THREAD

**Issue by Luxvao** [ostreedev/ostree#2724]
I was trying to build this on WSL, because it's a dependency, but I was unable to do so because gio-unix-2.0 is not on the 2.66 version I think. As it's a part of glib I don't know how to procede. As far as I know I can't just easily update the glib so it would be the version that's needed.
```
configure: error: Package requirements (gio-unix-2.0 >= 2.66.0) were not met:

Requested 'gio-unix-2.0 >= 2.66.0' but version of GIO unix specific APIs is 2.64.6

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```
Thanks

**Comment by dbnicholson** [comment]
I don't think this has anything to do with WSL. Either build a newer glib or start from a more recent Ubuntu base. If you need to build glib because there's no newer base, just install it in the same prefix that you're installing ostree in.

I don't think this is an ostree bug, so I'm going to close it. Feel free to reopen if you think it is.
