### ISSUE TITLE
different behavior ostree-2022.7 vs ostree-2023.1

### ISSUE THREAD

**Issue by runcom** [ostreedev/ostree#2840]
When building and installing an F37 IoT image with the following ostree (plus ignition) everything that we enable from osbuild seems to be working just fine and we get a correct config-diff. You can see the version below and the diff:

![image](https://user-images.githubusercontent.com/849915/226581830-26d84cf9-d18b-496f-8f2c-0f56c3968d14.png)
![image](https://user-images.githubusercontent.com/849915/226582016-7d981f59-5213-46fb-bdfa-125dda1a204e.png)

However, on F38 with ostree-2023.1, something that we enable as we used to gets deleted and config-diff is just different:

![image](https://user-images.githubusercontent.com/849915/226582153-5d8d7390-c8ef-47e2-9a29-f436db2b2f56.png)
![image](https://user-images.githubusercontent.com/849915/226582170-5274d547-3752-48c2-80f3-1759be225c58.png)

You can see two services are now `D` deleted (?) and we don't understand the change in behavior as both system share the same code when building and the only difference we see is just the ostree version difference.

cc @achilleas-k

**Comment by dbnicholson** [comment]
Are you sure this isn't an issue with your image builder or systemd? If I had to guess, this has more to do with the systemd preset being applied differently. Ostree doesn't touch and if those parts on its own.

**Comment by cgwalters** [comment]
There's https://fedoraproject.org/wiki/Changes/Preset_All_Systemd_Units_on_First_Boot thought that says it landed in 37.

I don't think ostree is going to be related here, though I still need to ship an updated ostree to 38 I think because of all the fallout from the new glib xref https://github.com/ostreedev/ostree/issues/2827

**Comment by runcom** [comment]
> There's https://fedoraproject.org/wiki/Changes/Preset_All_Systemd_Units_on_First_Boot thought that says it landed in 37.

in F37, according to that link, if I run `preset-all` I get stuff removed 

> On a newly installed system, with arbitrary set of packages: call systemctl preset-all. This should result in no changes.

so maybe it didn't land in F37 or the package with the "fix" isnt' there yet?

**Comment by runcom** [comment]
> so maybe it didn't land in F37 or the package with the "fix" isnt' there yet? it seems in F38 I'm indeed seeing https://fedoraproject.org/wiki/Changes/Preset_All_Systemd_Units_on_First_Boot

and I'm now wondering how to fix this too - my package has systemd services correctly wired in systemd macros

**Comment by cgwalters** [comment]
Right, with the change anyone using "real firstboot mode" will need to use presets.

**Comment by runcom** [comment]
> Right, with the change anyone using "real firstboot mode" will need to use presets.

thank you Colin for the info - one more question, how to you then handle the default target? does it follow simlar to this? I couldn't find reference in fedora-coreos-config other than https://github.com/coreos/fedora-coreos-config/blob/56d26da22547bd199363b0aa880fb5e4a8a81290/manifests/fedora-coreos-base.yaml#L45

**Comment by cgwalters** [comment]
> thank you Colin for the info - one more question, how to you then handle the default target? 

It should work to just change what `/usr/lib/systemd/system/default.target` points to for that, right?  I'm not aware of any changes in that area.

**Comment by cgwalters** [comment]
BTW, I only know about this stuff because it was *really really painful* to figure this all out in the time frame of originally creating FCOS, because as I said in [this comment](https://github.com/systemd/systemd/issues/8268#issuecomment-410234221) I believe Fedora CoreOS was the first Fedora-based thing to actually try to enable `ConditionFirstBoot`.  And it had a lot of knock-on consequences (the root filesystem writablility one was really confusing too).  

But basically as soon as you opt-in to this, everything writing a systemd unit at build ( or firstboot time as Ignition does) will also need to write a preset.

**Comment by dbnicholson** [comment]
It does if you take the policy that units are disabled by default. For Endless we do the opposite under the idea that if a package is included in the OS we usually want the units to be enabled. There are just a handful of units that we specifically stable in a system wide preset. But then Endless doesn't allow package layering or anything like that.

**Comment by cgwalters** [comment]
> It does if you take the policy that units are disabled by default.

Ah right...but isn't that a Debian thing because the Debian choice was that services *immediately start* after `apt install` (and to do that, you need debconf...) ?
