### ISSUE TITLE
Ostree-system-generator failed with exit status 1

### ISSUE THREAD

**Issue by Freyon77** [ostreedev/ostree#2909]
Arch x86_64

Every boot error message appear in journalctl. Sometimes error message shows randomly, but not sure what trigger it.

(sd-execu[4034]: /usr/lib/systemd/system-generators/ostree-system-generator failed with exit status 1.

**Comment by Freyon77** [comment]
Affected fedora users too

**Comment by chrisawi** [comment]
I saw a user report this earlier and meant to relay it here, but I got distracted by the flatpak issue.

Since https://github.com/ostreedev/ostree/commit/aa72caffb540114a0e8635ab2990b9c8b0b8f9db, that generator no longer exits 0 when not ostree-booted. The comment describing the intended behavior [is still present](https://github.com/ostreedev/ostree/blob/main/src/switchroot/ostree-system-generator.c#L61-L65):

```
  /* If we're installed on a system which isn't using OSTree for boot (e.g.
   * package installed as a dependency for flatpak or whatever), silently
   * exit so that we don't error, but at the same time work where switchroot
   * is PID 1 (and so hasn't created /run/ostree-booted).
   */
```

**Comment by Freyon77** [comment]
So as I understand it this is intentional and will not be corrected? It would be nice if there was an option to mask the error. Well I guess the only solution is to go back to the previous version

**Comment by dbnicholson** [comment]
@ericcurtin looks like the aboot systemd generator changes in aa72caffb540114a0e8635ab2990b9c8b0b8f9db cause the generator to fail on non ostree booting systems. Can you have a look?
