### ISSUE TITLE
gpg-verify-summary ignored with HTTPS URLs

### ISSUE THREAD

**Issue by LukeShortCloud** [ostreedev/ostree#3061]
When an ostree repo has `gpg-verify-summary=false` and the `url` is set to an HTTPS website, it still checks for the `summary.sig` file. It shows a misleading error that there was an SSL or SSH connection issue. The connection to the website works (I see the connection and 404 error in the HTTP server log), the `summary.sig` file simply does not exist for my repository because I never signed the `summary` file with GPG to generate the signature.

```
$ sudo vim /etc/ostree/remotes.d/foobar.conf
[remote "foobar"]
url=https://foobar.com/repo
gpg-verify=false
gpg-verify-summary=false
$ sudo rpm-ostree upgrade
error: While pulling fedora/38/x86_64/silverblue: While fetching https://foobar.com/repo/summary.sig: [60] SSL peer certificate or SSH remote key was not OK
```

However, with HTTP, it works as expected and skips checking for the `summary.sig` file. My system upgrade continues and completes without error.

```
$ sudo vim /etc/ostree/remotes.d/foobar.conf
[remote "foobar"]
url=http://foobar.com/repo
gpg-verify=false
gpg-verify-summary=false
$ sudo rpm-ostree upgrade
```

I am testing on Fedora Silverblue 38.

```
$ ostree --version
libostree:
 Version: '2023.6'
 Git: 0a60b238b7ae60ef411671b63ff3dfd8310b7b7a
 Features:
  - inode64
  - libcurl
  - libsoup
  - gpgme
  - composefs
  - ex-fsverity
  - libarchive
  - selinux
  - openssl
  - sign-ed25519
  - libmount
  - systemd
  - release
  - p2p
$ rpm-ostree --version
rpm-ostree:
 Version: '2023.7'
 Git: 06600cc4e215bed584ee71ff34bf5b78a181cab4
 Features:
  - rust
  - compose
  - container
  - fedora-integration
```

**Comment by dbnicholson** [comment]
> `error: While pulling fedora/38/x86_64/silverblue: While fetching https://foobar.com/repo/summary.sig: [60] SSL peer certificate or SSH remote key was not OK`

That looks like the HTTPS certificate isn't valid. It doesn't say anything about a GPG signature. Do you actually have a certificate for foobar.com?

**Comment by LukeShortCloud** [comment]
The error seems misleading. That file does not exist. I am actually using a private AWS S3 bucket (just using `foobar.com` here for simplicity) which has a verified SSL provided by Amazon.

- `curl https://foobar.com/repo/summary` = works
- `curl https://foobar.com/repo/summary.sig` = does not work, 404 error (expected as this file does not exist)
    - This is the GPG signature file for the summary file that ostree requires by default. I did not sign the repository and I am trying to avoid that for faster and easier testing purposes.

**Comment by dbnicholson** [comment]
I understand what you're trying to do and that's totally fine. The summary signature is optional, but I believe ostree tries to fetch it regardless in case you later change your remote configuration to verify it.

My experience with S3 is that it returns a 403 when a requested object doesn't exist instead of a 404 (unless you have a fully public policy). It's a sort of security by obscurity. But ostree already copes with both the 403 and the 404 in this scenario. At least it used to.

Is `[60] SSL peer certificate or SSH remote key was not OK` the error you actually get when using the S3 bucket? If so, that kinda seems like a bug in the curl fetcher. We've always used the soup backend at Endless and I'm fairly confident I've used this exact configuration in the past. Also, if it was really an issue with the 403/404, then the http:// fetch would fail in the same way. You can try running with `OSTREE_DEBUG_HTTP=1` to see exactly what's going on.

**Comment by LukeShortCloud** [comment]
Thanks for the help and insight!

I retested today and the problem went away. I also setup a new ostree repository at a different location (not hosted on S3). It worked there, too.

I'll go ahead and close this out. If it happens again, I know to use `OSTREE_DEBUG_HTTP=1` to help narrow down connection issues. Thanks again!
