### ISSUE TITLE
Failed to create /run/ostree: File exists

### ISSUE THREAD

**Issue by ericcurtin** [ostreedev/ostree#3122]
Seen on Qualcomm Automotive board by QE:

```
[    0.119955] Warning: unable to open an initial console.
[    2.909035] ostree-prepare-root[292]: ostree-prepare-root: sysroot.readonly=true requires /sysroot to be writable at this point
start OSTree Prepare OS/.
[    3.188183] ostree-prepare-root[297]: ostree-prepare-root: Failed to create /run/ostree: File exists
[FAILED] Failed to start OSTree Prepare OS/.
[    8.623764] ostree-prepare-root[304]: ostree-prepare-root: Failed to create /run/ostree: File exists
ot[315]: ostree-prepare-root: Fa[    2.909035] ostree-prepare-root[292]: ostree-prepare-root: sysroot.readonly=true requires /sysroot to be writable at this point
[FAILED] Failed to start     3.188183] ostree-prepare-root[297]: ostree-prepare-root: Failed to create /run/ostree: File exists
[FAILED] Failed to start  ostree-prepare-root[304]: ostree-prepare-root: Failed to create /run/ostree: File exists
[    8.662021] ostree-prepare-root[315]: ostre /run/ostree: File exists
[FAILED] Failed to

Generating "/run/initramfs/rdsosreport.txt"


Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
Yramfs/rdsosreport.txr mounting them and attach it to a bug report.
```

I might do a clean install and this might go away, but important to log this in case others see this issue regardless.

Sometimes I wonder should we log the error and not fail, that's always a tough debate, pros/cons

**Comment by cgwalters** [comment]
The fatal problem is 

> ostree-prepare-root: sysroot.readonly=true requires /sysroot to be writable at this point

Which is because you're probably missing `rw` on the kernel commandline.  Can you confirm?  This isn't the first instance of this I've seen recently; did something change in e.g. osbuild?  I see https://gitlab.com/CentOS/automotive/sample-images/-/blob/main/osbuild-manifests/include/image.ipp.yml#L40 ...

I think the failure to write `/run/ostree` may be because something in the initramfs is retriggering the run, and we're not idempotent right now.

**Comment by cgwalters** [comment]
(Feel free to reopen if I've missed something and there's an ostree bug here)

**Comment by ericcurtin** [comment]
We have both rw and ro, I think you are right, ro is probably overriding rw I guess

`rw loglevel=4 no_console_suspend=1 cd acpi=off net.namink.mode=skip console=ttyMSM0,115200,n8 systemd.show_status=auto libahci.ignore_sss=1 ostree=/ostree/boot.1/centos/e0cfdbbb336659ecf3ce51546e7deda64d08f34a90f6c132e442940ffdd4dddf/0 root=PARTLABEL=system_a androidboot.bootdevice=1d84000.ufshc androidboot.fstab_suffix=default aroidboot.baseband=apq androidboot.slot_suffix=_a skip_initramfs rootwait ro init=/sbin/init silent_boot.mode=nonsilent
`

**Comment by ericcurtin** [comment]
Also managed to get the full logs from QE

[journalctl.txt](https://github.com/ostreedev/ostree/files/13729513/journalctl.txt)

**Comment by cgwalters** [comment]
What is injecting `ro` then?  It should stop doing so.

**Comment by ericcurtin** [comment]
All Android bootloaders inject firmware, it's not the nicest design, but that's just what they do...

**Comment by cgwalters** [comment]
If that's the case...well, ideally it could be changed to stop doing so...

But if not, mmm...perhaps the behavior could be changed in dracut - I think around here https://github.com/dracutdevs/dracut/blob/4971f443726360216a4ef3ba8baea258a1cd0f3b/modules.d/99base/parse-root-opts.sh#L7 - to have both "rw" and "ro" actually mean "rw".  Although hm with a quick test here, that looks like the semantics today at least with current FCOS appending `ro` still works for me...though FCOS has a lot of special stuff around the root mount and we may not even use that dracut code; I'd need to dig in.

I would't be totally opposed to a patch to ostree-prepare-root which just forced on `rw` (instead of erroring out) regardless of what dracut did before that...perhaps just gated on the presence of the `androidboot` karg?  But it's obviously hacky.
