### ISSUE TITLE
signature duplicate checking not working

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#608]
Check this out:

```
$ ostree --repo=repo show app/org.gnome.gedit/x86_64/master
commit 39095f029c8c1ebbcff1676e4daf6714d74dc0b01a8f6c1665223938a402d633
Date:  2016-12-01 13:50:02 +0000

    Export org.gnome.gedit

$ ostree gpg-sign --repo=repo app/org.gnome.gedit/x86_64/master 6A2B067FB5E17A1A3FC8A0DAEB6216DDB76C70E9
$ ostree --repo=repo show app/org.gnome.gedit/x86_64/mastercommit 39095f029c8c1ebbcff1676e4daf6714d74dc0b01a8f6c1665223938a402d633
Date:  2016-12-01 13:50:02 +0000

    Export org.gnome.gedit

Found 1 signature:

  Signature made tor  1 dec 2016 15:59:42 using DSA key ID EB6216DDB76C70E9
  Can't check signature: public key not found
$ ostree gpg-sign --repo=repo app/org.gnome.gedit/x86_64/master 6A2B067FB5E17A1A3FC8A0DAEB6216DDB76C70E9
$ ostree --repo=repo show app/org.gnome.gedit/x86_64/mastercommit 39095f029c8c1ebbcff1676e4daf6714d74dc0b01a8f6c1665223938a402d633
Date:  2016-12-01 13:50:02 +0000

    Export org.gnome.gedit

Found 2 signatures:

  Signature made tor  1 dec 2016 15:59:42 using DSA key ID EB6216DDB76C70E9
  Can't check signature: public key not found

  Signature made tor  1 dec 2016 15:59:49 using DSA key ID EB6216DDB76C70E9
  Can't check signature: public key not found
```
See how it duplicated the signature? However if I use a shorter version of the key id it works:
```
$ ostree gpg-sign --repo=repo app/org.gnome.gedit/x86_64/master EB6216DDB76C70E9
error: Commit is already signed with GPG key EB6216DDB76C70E9
```
It ends up checking for the matching key in `ostree_gpg_verify_result_lookup` where it does `g_str_has_suffix (signature->fpr, key_id_upper)`, but in my case key_id_upper is longer than the fingerprint, so it doesn't match. Is the suffix match supposed to be the other way? Or are you supposed to be able to use an even shorter form of the fingerprint?

**Comment by ramcq** [comment]
Ruh roh... this is also broken with signing subkeys which is what we're using with Flathub. It re-signs every commit if we run an "open" flathub build-sign on our repo. :(

**Comment by ramcq** [comment]
@alexlarsson Strictly speaking, 6A2B067FB5E17A1A3FC8A0DAEB6216DDB76C70E9 is a fingerprint and not a key ID. There are two formats of key ID, 32-bit (short) and 64-bit (long). 32-bit is provably busted now in terms of establishing uniqueness, so gpg and ostree and stuff default to 64-bit now. I guess if we're doing a suffix match and 64-bits is deemed insufficient in future, we could internally consider the whole fingerprint for comparison but there is an argument this is simply user error. :)

**Comment by ramcq** [comment]
```
OT: queuing fetch of 7116fc85f8f5895b9cb40561e88ae86c1107804b980a76bdd2cf5d565931301e.commit (detached)


GPG: Verification enabled, found 1 signature:

  Signature made Wed 26 Jul 2017 03:29:11 BST using RSA key ID 562702E9E3ED7EE8
  Good signature from "Flathub Repo Signing Key <flathub@flathub.org>"

OT: fetch of 7116fc85f8f5895b9cb40561e88ae86c1107804b980a76bdd2cf5d565931301e.commit (detached) complete
OT: queuing fetch of 6c4f0c10509cf7fbb58a3716633b80c555baa2de7a98dd022f17f623c58fdb5e.commit (detached)

error: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)
```

Hmm - I'm not actually sure that there is an ostree problem after all - maybe there is something broken in the Flathub repo.

**Comment by ramcq** [comment]
(this is running `ostree -v --repo=/srv/flathub/repo pull --depth=-1 --mirror flathub` btw)

**Comment by ramcq** [comment]
Hmm, damn - this isn't quite working. I think we need to export the signing pubkey from the GPG context that the signing GPG is run in, and import it into the context that the verification is done in:
```[buildbot@repo ~]$ repo=/srv/repo
[buildbot@repo ~]$ gpg=/srv/gpg
[buildbot@repo ~]$ keyid=4184DD4D907A7CAE
[buildbot@repo ~]$ flatpak build-sign --ostree-verbose --gpg-sign=${keyid} --gpg-homedir=${gpg} ${repo}
XA: Could not find key ID 4184DD4D907A7CAE to lookup signature.
XA: Could not find key ID 4184DD4D907A7CAE to lookup signature.
XA: Could not find key ID 4184DD4D907A7CAE to lookup signature.
XA: Could not find key ID 4184DD4D907A7CAE to lookup signature.```

**Comment by cgwalters** [comment]
Also, now that I think about this I'm not totally sure about auto-canonicalizing the signing subkey under `OSTREE_GPG_SIGNATURE_ATTR_FINGERPRINT`; we're hiding the subkey information. I mean, it's probably generally good, but if e.g. the key starts having multiple signing subkeys (which is kind of the point of subkeys - you cna rotate them faster), debugging failures is going to get harder.

So maybe let's introduce `OSTREE_GPG_SIGNATURE_ATTR_FINGERPRINT_PRIMARY`?

**Comment by cgwalters** [comment]
In the short term, we could easily add an API to skip signing if there are any existing signatures.

**Comment by ramcq** [comment]
Hmm - I can see your point arguments both ways. GPG does talk about the signature key (subkey) and the signing ID distinctly:
```[buildbot@repo ~]$ GNUPGHOME=/srv/gpg gpg --verify foo.gpg 
gpg: Signature made Wed 02 Aug 2017 14:39:26 UTC using RSA key ID E3ED7EE8
gpg: Good signature from "Flathub Repo Signing Key <flathub@flathub.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 6E5C 05D9 79C7 6DAF 93C0  8135 4184 DD4D 907A 7CAE
     Subkey fingerprint: 54A6 CDDD 8919 FB20 4200  D8AC 5627 02E9 E3ED 7EE8```

Arguably the API is conflating the key with the signature, but perhaps most relevantly it does return the signing key ID, and also the UID info from the primary key, and the fingerprint of both. I can cook a patch for _FINGERPRINT_PRIMARY but we should also have ostree_gpg_verify_result_describe_variant show it in the case it != _FINGERPRINT. Any preferences where that appears? "(key ID XXXXXXXXXXXX)" after "Good signature from..." if they differ?

For the real bug (rather than just displaying the right key IDs), your workaround isn't quite right for flathub because we're intentionally trying to add our signature on top of the upstream signatures in some cases. I don't think we need API changes however, we could either:
1. Always add the signing key as a trusted key to the repo before doing any of the other operations, on the basis that if you can't trust yourself...
1. Do that but just internally at run time, so maybe inside ostree_repo_sign_commit we split sign_data to load the key first, provide it to _ostree_repo_gpg_verify_with_metadata to load into the verify context, before proceeding?
1. If the repo doesn't have it's signing key as a trusted key, add a fallback for the case we can't canonicalise the signing key, add instead use the uppercase & substring functionality as a fallback, but check against both the primary and the subkey fingerprints.

Open to suggestions on the preferred approach.

**Comment by ramcq** [comment]
Oh - Tobi also pointed out that in the case the signature is present but is invalid, maybe ostree_gpg_verify_result_lookup shouldn't return the result... because it's not actually signed. Or, at the very least gpg sign should check for validity and expiration before it decides not to sign. Because if you have expired sigs, you do want it to sign again.

**Comment by ramcq** [comment]
I realised from my above list that 3 wouldn't actually fix the problem because without the key, the verifying context can never map between the two IDs, substring or not. But it turns out 2 is way easy because the verify function already takes a directory to look for keys in, so I've got a WIP which I'll do some testing on today.

**Comment by ramcq** [comment]
So this is looking good now, I've run this code and not run into any more duplicate signatures. \o/

The only remaining problem I found when thinking about clearing off the duplicates from the repo, is that if you specify a subkey ID to ostree gpg-sign -d then it will probably a) fail to match anything due to not being able to canonicalise the key at all (we'd need to feed the homedir down to the verifier), and b) even if it did, then it would erase _all_ signatures from any subkey of the ID you specified, not just the specific subkey you provided (possibly intentionally).

I think this means "lookup" is too magic now and in fact, the canonicalisation should only be performed one way, so that a subkey signature lookup will also match the primary key ID, but if you specify a subkey ID to look for it will not match unless it has that subkey signature - we should just check the search key against the primary key fingerprint (if present) in addition to the signature fingerprint. Thoughts?

**Comment by ramcq** [comment]
PR with those patches. Should work with this in terms of avoiding duplicate signatures etc, but lookup is a little too eager. One more patch needed so that subkey signatures match primary key ID searches, but not vice versa - otherwise you can't use gpg-sign --delete to take a specific subkey signature off. Might be worth a separate ticket at this point though. :)
